name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4
#descargar node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalar dependencias
      run: npm install
#correr la pagina
    - name: Build de la app
      run: npm run build

    - name: Levantar servidor
      run: npm run start &

    - name: Esperar a que esté listo
      run: npx wait-on http://localhost:3000

#pruebas de humo API
    - name: Instalar Newman
      run: npm install -g newman

    - name: Ejecutar pruebas de humo
      run: newman run pruebas_humo_api_drs.json

#pruebas playwright con pytest
    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias de Python
      run: |
          python install pytest-playwright pytest-html
          playwright install

    - name: Ejecutar pruebas de Playwright
      run: pytest --html=reporte_pruebas.html --self-contained-html 
    
    - name: Subir reporte Playwright
      uses: actions/upload-artifact@v4
      with:
        name: reporte-pruebas-playwright
        path: reporte_pruebas.html