name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalar dependencias
      run: npm install

    - name: Build de la app
      run: npm run build

    - name: Levantar servidor
      run: npm run start &

    - name: Esperar a que esté listo
      run: npx wait-on http://localhost:3000

    - name: Instalar Newman
      run: npm install -g newman

    - name: Ejecutar pruebas de humo
      run: newman run pruebas_humo_drs.json

